name: Avalonia Cross-Platform Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        configuration: [Debug, Release]

    runs-on: ${{ matrix.os }}

    env:
      Solution_Name: YouTubeThumb.sln
      Project_Name: YouTubeThumb.csproj  # Adjust if your .csproj has a different name
      DOTNET_VERSION: 8.0.x

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    # Build the application (without RID)
    - name: Build Application
      run: |
        dotnet build ${{ env.Solution_Name }} \
          -c ${{ matrix.configuration }} \
          --no-restore

    # Optional: Run tests if you have any
    - name: Run Tests
      run: dotnet test ${{ env.Solution_Name }} --no-build -c ${{ matrix.configuration }}
      if: success()

    # Publish the application (with platform-specific RID, targeting the .csproj)
    - name: Publish Application
      run: |
        dotnet publish ${{ env.Project_Name }} \
          -c ${{ matrix.configuration }} \
          -r ${{ matrix.os == 'windows-latest' && 'win-x64' || matrix.os == 'macos-latest' && 'osx-x64' || 'linux-x64' }} \
          --self-contained true \
          --no-build \
          -o ./publish/${{ matrix.os }}-${{ matrix.configuration }}

    # Upload build artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: YouTubeThumb-${{ matrix.os }}-${{ matrix.configuration }}
        path: ./publish/${{ matrix.os }}-${{ matrix.configuration }}
